library(dplyr)
library(lubridate)
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", "power_consumption.zip")
unzip("power_consumption.zip")
HPC <- read.csv("household_power_consumption.txt", sep = ";", na.strings = "?")
HPC  <- tbl_df(HPC)
HPC$Date  <- dmy(HPC$Date)
HPC$Time  <- hms(HPC$Time)
HPC2  <- filter(HPC, Date >= "2007-02-01" & Date <= "2007-02-02")
png("Plot1.png", width = 480, height = 480, units ="px")
hist(HPC2$Global_active_power, main ="Global Active Power", xlab ="Global Active Power (kilowatts)", col = "red")
dev.off()
