library(dplyr)
library(lubridate)
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", "power_consumption.zip")
unzip("power_consumption.zip")
HPC <- read.csv("household_power_consumption.txt", sep = ";", na.strings = "?")
HPC  <- tbl_df(HPC)
HPC$Date  <- dmy(HPC$Date)
HPC$Time  <- hms(HPC$Time)
HPC2  <- filter(HPC, Date >= "2007-02-01" & Date <= "2007-02-02")
png("Plot4.png", width = 480, height = 480, units ="px")
par(mfrow = c(2,2))
plot(HPC2$Date + HPC2$Time, HPC2$Global_active_power, type = "l", xlab ="", ylab = "Global Active Power")
plot(HPC2$Date + HPC2$Time, HPC2$Voltage, type = "l", xlab ="datetime", ylab = "Voltage")
with(HPC2, plot(Date + Time, Sub_metering_1, type ="l", xlab="", ylab = "Energy sub metering"))
with(HPC2, lines(Date + Time, Sub_metering_2, type ="l", col = "red"))
with(HPC2, lines(Date + Time, Sub_metering_3, type ="l", col = "blue3"))
legend("topright", col = c("black","red", "blue3"),legend = names(HPC2)[7:9], lty = 1, bty ="n")
plot(HPC2$Date + HPC2$Time, HPC2$Global_reactive_power, type = "l", xlab ="datetime", ylab ="Global_reactive_power")
dev.off()
